### ISSUE TITLE
Dynamic Ports Not on NetworkInfo

### ISSUE THREAD

**Issue by richardhanson** [pytest-docker-compose/pytest-docker-compose#8]
When using dynamic port allocation, the ports are not on the containers so they can't be pulled into the `NetworkInfo`. Refetching the containers and using `ports` instead of `.get("HostConfig.PortBindings")` seems to do the trick. My `docker_network_info` looks like

```python
@pytest.fixture
def docker_network_info(self, docker_containers: typing.List[Container], docker_project):
    """Returns hostnames and exposed port numbers for each container so tests can use them.

    The Project must be recreated when using dynamic port mappings in order to fetch the port.
    If this is not done, the host_port will not be populated.
    """
    containers = docker_project.containers()
    return {
        container.name: [
            NetworkInfo(
                container_port=container_port,
                hostname=port_config["HostIp"] or "localhost",
                host_port=port_config["HostPort"],
            )

            # Example::
            #
            #   {'8181/tcp': [{'HostIp': '', 'HostPort': '8182'}]}
            for container_port, port_configs
            # in container.get("HostConfig.PortBindings").items()
            in container.ports.items()

            for port_config in port_configs
        ]

        for container in containers
    }
```

Tested with both dynamic ports and ones set in the compose file. If these changes look agreeable, let me know and I'll raise a PR.

**Comment by todofixthis** [comment]
Also, what version of `docker-compose` do you have installed?

**Comment by richardhanson** [comment]
Here's what I'm currently working with
```
python - 3.7.3
pytest - 4.4.2
docker-compose - 1.24.0
```

I pushed a branch up that has a new test that fails both with and without the containers already running. It passes if containers are already running with the `ports` change but still fails if pytest brings up the containers. Not sure why.

**Comment by richardhanson** [comment]
I distilled the data down a bit to show the differences using 
`{'name': container.name, 'network': {'HostConfig': container.get('HostConfig.PortBindings'), 'ports': container.ports}}`

Starting the container from pytest I get:
```python
[{
    'name': 'my_network_my_api_service_1',
    'network': {
        'HostConfig': {
            '5000/tcp': [{
                'HostIp': '',
                'HostPort': '5000'
            }]
        },
        'ports': {}
    }
}, {
    'name': 'my_network_my_db_1',
    'network': {
        'HostConfig': {
            '5432/tcp': [{
                'HostIp': '',
                'HostPort': '5432'
            }]
        },
        'ports': {}
    }
}, {
    'name': 'my_network_db_without_port_1',
    'network': {
        'HostConfig': {
            '5432/tcp': [{
                'HostIp': '',
                'HostPort': ''
            }]
        },
        'ports': {}
    }
}]
```

Containers already running:
```python
[{
    'name': 'my_network_my_api_service_1',
    'network': {
        'HostConfig': {
            '5000/tcp': [{
                'HostIp': '',
                'HostPort': '5001'
            }]
        },
        'ports': {
            '5000/tcp': [{
                'HostIp': '0.0.0.0',
                'HostPort': '5001'
            }]
        }
    }
}, {
    'name': 'my_network_my_db_1',
    'network': {
        'HostConfig': {
            '5432/tcp': [{
                'HostIp': '',
                'HostPort': '5433'
            }]
        },
        'ports': {
            '5432/tcp': [{
                'HostIp': '0.0.0.0',
                'HostPort': '5433'
            }]
        }
    }
}, {
    'name': 'my_network_db_without_port_1',
    'network': {
        'HostConfig': {
            '5432/tcp': [{
                'HostIp': '',
                'HostPort': ''
            }]
        },
        'ports': {
            '5432/tcp': [{
                'HostIp': '0.0.0.0',
                'HostPort': '33412'
            }]
        }
    }
}]
```

This might be a bug in `docker-compose` that needs to be addressed instead of here.

**Comment by richardhanson** [comment]
I discovered today that the docs for [`docker inspect`](https://docs.docker.com/engine/reference/commandline/inspect/) reference the `NetworkSettings.Ports` config instead of `HostConfig.PortBindings`. 
This is the example for getting all ports:
```
docker inspect --format='{{range $p, $conf := .NetworkSettings.Ports}} {{$p}} -> {{(index $conf 0).HostPort}} {{end}}' $INSTANCE_ID
```

May be worth switching to that however it doesn't seem to work any better.

**Comment by RmStorm** [comment]
If it properly gets the ports when pytest-docker-compose starts the containers and it is the recommendation of the official docs it's probably worthwhile to switch to that. It doesn't look like a big change? I can spend some time on it tomorrow I think.

**Comment by RmStorm** [comment]
Ok I think I've solved the issue. The line:
https://github.com/pytest-docker-compose/pytest-docker-compose/blob/1c0f9a50c8a7f42d054445ab218f81aebcd19fbf/src/pytest_docker_compose/__init__.py#L163
returns the containers the way they look directly after creation. Since you want to access dynamically created ports the dictionary returned here:
https://github.com/pytest-docker-compose/pytest-docker-compose/blob/1c0f9a50c8a7f42d054445ab218f81aebcd19fbf/src/pytest_docker_compose/__init__.py#L169
will need to dynamically fetch the containers each time a piece of code tries to use the containers.

So I've written a solution for this. I have subclassed `dict` and made it read only and I overrode the `__getitem__` to fetch containers everytime they are used. It is the difference between running `docker inspect` once and storing the result or rerunning `docker inspect` every time the containers are accessed.

There is just one problem with the solution I wrote, the method `docker_project.containers(service_names=['my_api_service'])` uses the service name to select containers. However we use `container.name` as the key for the container dictionary, this looks like: `'my_network_my_api_service_1'`. So, I could do some string parsing to resolve this but I think that would be fragile. I prefer to fetch all containers everytime any container is used. Fetching the details of a single container takes .03 seconds so I think the overhead of fetching all containers every time is acceptable.

**Comment by RmStorm** [comment]
@richardhanson can you take a look at #24 and let me know if this indeed solves your problem? If it does you can merge it into dev I think. And if it solves your issue can you maybe also write a test that actually uses this code? I think if those two things are done we can merge to master.

**Comment by richardhanson** [comment]
I'll take a look later today. Good find!

**Comment by RmStorm** [comment]
I was talking this over with a colleague and he thought that maybe this isn't the best idea. Subclassing dict seemed like a pretty good idea because it behaves kinda backwards incompatible. However since essentially docker inspect is rerun each time now the results can differ, that means that this change should actually involve a bump of the major version.

If the major version needs bumping anyway it might be nicer to pass functions in a regular dict instead of containers in this subclassed dict I made. That makes it much more explicit that the container is refetched everytime, so something like:
```python
api_container = function_scoped_containers["my_network_my_api_service_1"]()
service = api_container.network_info[0]
```
What do you guys think? @richardhanson @todofixthis

**Comment by todofixthis** [comment]
I like the idea.  What do you think about this for the syntax?

```python
api_container = function_scoped_containers.get("my_network_my_api_service_1")
```

**Comment by RmStorm** [comment]
> I like the idea. What do you think about this for the syntax?
> 
> ```python
> api_container = function_scoped_containers.get("my_network_my_api_service_1")
> ```

yes, that looks pretty good. Maybe we can switch to using the service name as defined in the docker compose file like so:
```python
api_container = function_scoped_containers.get("my_api_service")
```
Since the change is backwards incompatible eitherway, I like this a little better. Using the full name seems a little redundant e.g. always having to include the network name. We know we are in the correct network since the project has been created from the indicated docker compose file.

What do you think?

**Comment by todofixthis** [comment]
> Since the change is backwards incompatible eitherway, I like this a little better. Using the full name seems a little redundant e.g. always having to include the network name. We know we are in the correct network since the project has been created from the indicated docker compose file.

Good shout.  I like this idea a lot.

**Comment by RmStorm** [comment]
Ok, so I wrote that. But now I'm thinking the fixture names should be changed to something like:
`function_scoped_container_fetcher` since it's no longer a dictionary? It's not very important but it might be a little clearer.

**Comment by todofixthis** [comment]
I wish it had a shorter name, and now we want to make it longer 😹

Hm.  If we are going to change the name, this would be the time to do it.

Might be more intuitive if the verbs matched; i.e. `function_scoped_container_getter.get(...)` or `function_scoped_container_fetcher.fetch(...)`

**Comment by RmStorm** [comment]
Yeah, I completely agree. Shorter would be nicer, but it should still be descriptive. I don't like cryptic names. Do you have any other suggestions?

**Comment by todofixthis** [comment]
There are only two hard things in computer science... 😹

🤔 The only other noun that comes to mind is 'proxy'.

Alternatively:  Is the fact that the fixture fetches container info on demand actually an implementation detail?  Would a developer write their tests differently if they were aware of this?

**Comment by todofixthis** [comment]
@RmStorm Is the `dynamic-ports` branch good to be deleted?
